### PR TITLE
Potato cannot be overcooked

### PR DESCRIPTION
**Pull request by ainsey11**
I don't like overcooked potatoes.

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Do you even know Java?

**Comment by TheDiamondYT1** [comment]
**Close** @drtshock

**Comment by TheDiamondYT1** [comment]
@ainsey11 This file is an enum; a list, basically. And every option in the list **except the last one** has a comma after it

**Comment by ainsey11** [comment]
Yeah, I realised that haha, I've created a patch on my fork, will raise a new PR

similar to arrays etc :)

**Pull request closed without merging**
