### PR TITLE
DuckDuckGo > Google

### PR DESCRIPTION
**Pull request by WilliDieEnte**
The hand-picked and fresh Potatoes are brought by the Duck :3

### CODE REVIEW

**Comment by UnknownRebell** [comment]
Yeah, its really important that the potatoes are brought by the duck!
they taste so good :>

**Comment by MiniDigger** [comment]
duplicate of #118

**Comment by WilliDieEnte** [comment]
Oh yeah, Sorry, didn't see that xd

Would still be cool tho. Fresh Potatoes brought by a cute Duck, who could say no to that? :o

**Comment by drtshock** [comment]
Duplicate

**Pull request closed without merging**
