### PR TITLE
Pepperoni for potato-pizza goodness

### PR DESCRIPTION
**Pull request by MattsLab**

### CODE REVIEW

**Comment by jkcclemens** [comment]
I'm going to go ahead and say -1. That sounds gross. Will wait for more opinions, though.

**Comment by Ichbinjoe** [comment]
As per the readme, this is a mainstream potato. Unless you were to also build in support of an actual pizza construct within the Potato project, I don't believe this topping exists within the potato ecosystem. And send me a picture of where dominos allows you to put potatoes on their pizza.

**Comment by MattsLab** [comment]
I was thinking more of a potato pizza, the potato being the crust.
yum

**Comment by Ichbinjoe** [comment]
Interesting... regardless, I think the preparation of this type of potato is too radically different to simply declare it as a topping to the potato. I believe this may be appropriate for an inheriting class of Potato.

Of course, other people may also weigh in.

**Comment by jkcclemens** [comment]
>inheriting class of Potato

+1

**Comment by drtshock** [comment]
potato can be extended if you want pizza.

**Comment by jkcclemens** [comment]
No activity for almost a month. Closing.

**Pull request closed without merging**
