### PR TITLE
More Bacon is always needed!

### PR DESCRIPTION
**Pull request by wherkamp**
More Bacon Man! More BACON!

### CODE REVIEW

**Comment by MiniDigger** [comment]
bacon is bad for you, I don't think that more bacon is a good idea, see https://www.huffingtonpost.com/2013/11/12/bacon-facts_n_4241592.html

**Comment by drtshock** [comment]
This is a very political PR.

**Comment by wherkamp** [comment]
How dare you, @MiniDigger , question the need of bacon?

**Comment by wherkamp** [comment]
I don't see the bacon being approved. Don't me me throw a potato. 🥔

**Comment by wherkamp** [comment]
throw new Potato ();.

**Comment by wherkamp** [comment]
Come on accept this pr

**Comment by wherkamp** [comment]
Now compatible with Onions.

**Pull request closed without merging**
