### PR TITLE
The potato expired. So it has to be removed.

### PR DESCRIPTION
**Pull request by MathisSanders**
I vouch! 👍

### CODE REVIEW

**Comment by kingdevnl** [comment]
Vouch! 👍
Lmao now i do it back you you @MathisSanders

**Comment by MiniDigger** [comment]
Requesting repo ban

**Comment by MathisSanders** [comment]
?

**Comment by kingdevnl** [comment]
it isnt funny anymore @MathisSanders So please just stop with spamming
It was fun in the begin but now it isn't anymore.

**Comment by MathisSanders** [comment]
Lmao

**Comment by MiniDigger** [comment]
This repo deals with a serious matter, please stop fooling around.

**Comment by MathisSanders** [comment]
This rope is one big joke. So why can't I be funny?

**Comment by SupaHam** [comment]
ur personality is a joke

**Comment by jkcclemens** [comment]
In other news, a PR deleting the whole repo is 0/10.

**Comment by MathisSanders** [comment]
Vouch! 👍

**Pull request closed without merging**
