### PR TITLE
Add Me Pls

### PR DESCRIPTION
**Pull request by SkepticalPotato2k**
I Love Potatoes So Add Me!

### CODE REVIEW

**Comment by MiniDigger** [comment]
you seem to misunderstand what contributors means

**Comment by SkepticalPotato2k** [comment]
lol i will contribute

**Comment by alyssadev** [comment]
Technically if this PR is merged SkepticalPotato2k will be a contributor, thereby retroactively making this PR valid

**Comment by drtshock** [comment]
I agree this PR is technically valid

**Pull request merged**
