### PR TITLE
Update maven plugins and drop java 1.6 support

### PR DESCRIPTION
**Pull request by MiniDigger**
We got a modern Potato over here!

### CODE REVIEW

**Comment by drtshock** [comment]
But java 6 would take away potato from people that haven't updated.

**Comment by MiniDigger** [comment]
buuut 6 is EOL and not many ppl use it anymore: https://plumbr.eu/wp-content/uploads/2015/04/java-version-statistics-over-time.png

**Comment by Ichbinjoe** [comment]
There is no reason to update potato. It functions perfectly fine with Java 6
On Mon, Mar 21, 2016 at 4:22 PM MiniDigger <notifications@github.com> wrote:

> buuut 6 is EOL and not many ppl use it anymore:
> https://plumbr.eu/wp-content/uploads/2015/04/java-version-statistics-over-time.png
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/drtshock/Potato/pull/79#issuecomment-199460218>
>
-- 
Joseph Hirschfeld
joe@ibj.io
Ichbinjoe
Skype: ichbinjoehirschfeld

**Comment by MiniDigger** [comment]
got a newer statistic here: http://puu.sh/nOWsn/9d89884a65.png

**Comment by drtshock** [comment]
Not sure how reliable puush is as a source.

**Comment by Zbob750** [comment]
Many people using potato are potato farmer who can't afford Java 7 or Java 8. Their life is potato. You cannot take away. Please decline :-1:

**Comment by drtshock** [comment]
I agree with bob

**Comment by AeSix** [comment]
Why are we not updated to Java 1.9 yet? https://jdk9.java.net/ *hmmph*

**Comment by MiniDigger** [comment]
@AeSix "Our potato is a mainstream potato; it doesn't enjoy being full of obscure code/references (not a hipster potato)."

**Comment by xXAndrew28Xx** [comment]
@MiniDigger How do a negative amount of people use Java 6?

**Comment by MiniDigger** [comment]
@xXAndrew28Xx I did not make that statistic, go ask the guys over at Puush who seem to have published that chart.

**Comment by armanoth** [comment]
Requesting PR close.

**Pull request closed without merging**
