### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OmriOn**
Updated README.md

### CODE REVIEW

**Comment by OmriOn** [comment]
ty for not approving LOL

**Comment by itsokk** [comment]
you said "potatos" buddy

**Review by wafflecoffee — CHANGES_REQUESTED** [review]
The plural of potato is potatoes; not potatos.
When writing about such a magnificent thing, you must ensure your grammar, spelling, etc. are all eloquently worded and perfect, especially when proposing changes.
Quite frankly, you should be ashamed of yourself for causing such a wrongdoing. Everything else is elegant, but the mistake you made was so atrocious that it takes away from the brilliantness of the proposition.
Change it as soon as you possibly can, lest you get striken down by the Potato Gods.

**Comment by OmriOn** [comment]
> The plural of potato is potatoes; not potatos.
> When writing about such a magnificent thing, you must ensure your grammar, spelling, etc. are all eloquently worded and perfect, especially when proposing changes.
> Quite frankly, you should be ashamed of yourself for causing such a wrongdoing. Everything else is elegant, but the mistake you made was so atrocious that it takes away from the brilliantness of the proposition.
> Change it as soon as you possibly can, lest you get striken down by the Potato Gods.

Sorry

**Review by wafflecoffee — APPROVED** [review]
Your competence in this matter is duly appreciated.

**Comment by drtshock** [comment]
Sorry but I do not chive with this.

**Comment by keystove** [comment]
> Sorry but I do not chive with this.

?

> **CHIVE**:
a widely cultivated small Eurasian plant related to the onion, with purple-pink flowers and dense tufts of long tubular leaves that are used as a culinary herb.

~ some source

**Pull request closed without merging**
