### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Bluscream**
https://github.com/drtshock/Potato/pull/100/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

### CODE REVIEW

**Comment by TekkitCommando** [comment]
What ever happened to describing PR's. :P

**Comment by MiniDigger** [comment]
before anyone else needs to look, this pr changes the image in the readme to 


I am 👎 on this, I like the current image more and think it fits better.

**Comment by Bluscream** [comment]
@MiniDigger i don't thnk you get the joke...

**Comment by MiniDigger** [comment]
@Bluscream this is a very serious project, there is no place for jokes here

**Comment by drtshock** [comment]
Not sure how anyone could think this is funny.

**Comment by Bluscream** [comment]
You retard

**Comment by MiniDigger** [comment]
-> reacts to his own comments
->  calls other ppl retards

**Comment by TekkitCommando** [comment]
lol

**Pull request closed without merging**
