### PR TITLE
Added Couch Potato

### PR DESCRIPTION
**Pull request by Xorgon**

### CODE REVIEW

**Comment by drtshock** [comment]
no implementation?

**Comment by Xorgon** [comment]
I can't think of an implementation right now but I thought it was pretty cool so I added it to make it available to all the other cool people around here.

**Comment by drtshock** [comment]
i think that's a good implementation considering tbh

**Comment by jkcclemens** [comment]
I'm on the *no* side of this PR. Useless image in the repo doesn't do much for me.

**Comment by jkcclemens** [comment]
Closing, as it provides no functionality.

**Pull request closed without merging**
