### PR TITLE
Adding isFried

### PR DESCRIPTION
**Pull request by cindyker**
Definitely need to check if the Potato isFried.

### CODE REVIEW

**Comment by jkcclemens** [comment]
Please follow conventions (`this.` before methods, spaces in `if` blocks, braces in `if` blocks, etc.). The nested if could be `&&`'d, as well.

This *may* be better suited in a `FriedPotato` class.

**Comment by Ichbinjoe** [comment]
In addition, the last line's conditional can be directly returned.

**Comment by Ichbinjoe** [comment]
Also, make sure you configured your local git correctly. The commit email for the last commit is illegal-email-address...

**Comment by jkcclemens** [comment]
No activity for almost a month. Closing.

**Pull request closed without merging**
