### PR TITLE
Remove unneccessary final

### PR DESCRIPTION
**Pull request by j0ach1mmall3**
Removes unneccessary final

### CODE REVIEW

**Comment by xXAndrew28Xx** [comment]
What if someone accidentally changes the variable ;(
http://stackoverflow.com/questions/137868/using-final-modifier-whenever-applicable-in-java

**Comment by j0ach1mmall3** [comment]
Nobody accidentally changes a variable... also either have final everywhere in the project, or nowhere, either is fine by me

**Comment by TheDiamondYT1** [comment]
Somebody might accidently change the Potato to something healthly, like a banana 😠

**Comment by drtshock** [comment]
Last comment sold me on this commit.

**Comment by TheDiamondYT1** [comment]
That comment was against it

**Comment by xXAndrew28Xx** [comment]
Lol

**Comment by drtshock** [comment]
oshit. didn't look at the code and read it backward :( incoming revert

**Pull request merged**
