### PR TITLE
Added the possibility to boil the potato if you have no oven

### PR DESCRIPTION
**Pull request by SimonBaars**
Not all people have an oven, and potatoes can still be delicious if you boil them.

### CODE REVIEW

**Comment by drtshock** [comment]
Please use spaces, not tabs.

**Comment by ronneke1996** [comment]
I have formatted the code so it uses spaces instead of tabs.

**Comment by drtshock** [comment]
ty so much

**Comment by TheDiamondYT1** [comment]
Add a way to microwave potato

**Comment by TheRealSimJoo** [comment]
Sounds good. And how is the succes of microwaving a potato determined?

**Comment by TheDiamondYT1** [comment]
Idk. I only come here to make potato jokes

**Comment by TheRealSimJoo** [comment]
This is serious business you know. The potato business will probably become a billion dollar business.

**Comment by TheDiamondYT1** [comment]
I know i also give potato counselling because some people want to make them too bloated with apache commons.

**Comment by TheRealSimJoo** [comment]
Freaking hipsters...

**Comment by TheDiamondYT1** [comment]
I know right

**Review by Scutua — APPROVED** [review]

**Pull request merged**
