### PR TITLE
add OVERCOOKED NotDeliciousReason

### PR DESCRIPTION
**Pull request by 7we**
my oven tends to run a little high.

### CODE REVIEW

**Comment by wherkamp** [comment]
So why not just pull your potato out early.

**Comment by 7we** [comment]
perhaps i should have created a SenseOfTimeNotFoundException

**Comment by kadenscott** [comment]
I think this would be a good addition. You can't always guarantee that you'll have a perfectly cooked potato, often times I find my baked potatoes are undercooked or overcooked.

+ there's already an UNDERCOOKED value

**Comment by drtshock** [comment]
ty

**Pull request merged**
