### PR TITLE
Gradleify potato.

### PR DESCRIPTION
**Pull request by pocakking**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
WHO LIKES GRADLE

**Comment by drtshock** [comment]
why :(

@cnr is this a good idea?

**Comment by TheDiamondYT1** [comment]
Maven fte

**Comment by TheDiamondYT1** [comment]
Ftw

**Comment by jkcclemens** [comment]
Too much Gradle bloat.

-1

**Comment by TheDiamondYT1** [comment]
Gradle burns potatoes, whereas maven cooks them perfectly.

\- Bill Gates

**Comment by drtshock** [comment]
Can't argue with bill gates

**Comment by TheDiamondYT1** [comment]
@falukerites You do know it is physically to have *The terrible gradle (TM)* in the same directory as *The awesome Maven (TM)*!!

**Comment by jamy015** [comment]
The logo of Maven is a feather. Potatoes are not very delicious if there are feathers inside...

In contrast, the logo of Gradle is an elephant. All glory to the ~~HypnoToad~~ [PotatoElephant](http://i.dailymail.co.uk/i/pix/2013/03/27/article-2299953-18F2B589000005DC-637_634x399.jpg)

**Comment by TheDiamondYT1** [comment]
Nah

**Comment by Trickster489** [comment]
@jamy015 There are several Maven logos, are you also suggesting that [plain text](https://en.wikipedia.org/wiki/Apache_Maven#/media/File:Maven_logo.svg) isn't delicious? If it isn't, there's no point in this entire project.

**Pull request closed without merging**
